export type Project = {
  id: string;
  title: string;
  category: "Residential" | "Commercial";
  tags: string[];
  location: string;
  year: string;
  image: string;
  slug: string;
  description: string;
  lead: string;
  editorialKicker: string;
  designResponse: string;
  details: string[];
  coverPosition?: string;
  images: string[];
  imageCaptions: string[];
};

export function getProjectHeroImage(project: Project): string {
  if (project.slug === "greenwich-west" && project.images[0]) {
    return project.images[0];
  }

  return project.image;
}

export const projects: Project[] = [
  {
    id: "8",
    title: "Head of the Harbor",
    category: "Residential",
    tags: ["Estate", "Renovation"],
    location: "Long Island, New York",
    year: "2024",
    image: "/images/projects/Head of the Harbor /PS_HeadofHarbor_2306_Final.jpg",
    slug: "head-of-the-harbor",
    editorialKicker: "Recent Work",
    lead: "A layered estate renovation where architectural calm meets art, custom millwork, and collected rooms built for daily living.",
    description:
      "A Long Island estate reworked with quiet confidence: tailored paneling, sculptural lighting, considered art placement, and rooms that feel composed without becoming formal.",
    designResponse:
      "The design language centers on restraint and texture. Pale woods, weighty dark accents, hand-finished surfaces, and moments of saturated blue create a house that feels established, personal, and current.",
    details: [
      "Custom millwork and paneling give new rooms a sense of permanence.",
      "Vintage silhouettes and modern art keep the house from feeling newly decorated.",
      "Layered window treatments soften the architecture and control the Long Island light.",
    ],
    coverPosition: "center",
    images: [
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1592_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1609_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1632_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1651_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1842_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1873_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1918_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1958_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1501_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1533_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1508_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1984_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2014_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2038_Final_Lights.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2064_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2114_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2151_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2159_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2255_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2230_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2212_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2200_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2271_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_1948_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2284_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2320_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2297_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2329_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2352_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2355_Final_Lights_2.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2372_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2542_Final.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor__DSF5629.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor__DSF5634.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor__DSF5636.jpg",
      "/images/projects/Head of the Harbor /PS_HeadofHarbor_2179_Final.jpg",
    ],
    imageCaptions: [
      "The estate exterior establishes the project's sense of scale and permanence.",
      "",
      "A framed view into the dining room reveals the house's central tension: tailored architecture, expressive art, and living materials.",
      "Layered dining details create intimacy inside a generous plan.",
      "",
      "",
      "Quiet paneling, filtered light, and sculptural objects carry the story room to room.",
    ],
  },
  {
    id: "9",
    title: "Houston Residence",
    category: "Residential",
    tags: ["New Construction", "Estate"],
    location: "Houston, Texas",
    year: "2024",
    image: "/images/projects/Houston/PeterS_Houston_2478_Final.jpg",
    slug: "houston",
    editorialKicker: "New Construction",
    lead: "A large-scale residence softened through material warmth, tailored furnishing, and moments of color that feel collected over time.",
    description:
      "A Houston residence composed around gracious rooms, curated art, expressive floral moments, and a palette that balances architectural polish with warmth.",
    designResponse:
      "The work avoids the blankness that can come with new construction. Rich stone, woven window treatments, custom upholstery, and artful object placement give the home a layered point of view from the start.",
    details: [
      "Large rooms are grounded with texture rather than excess ornament.",
      "Art and objects create intimacy inside the home's scale.",
      "Natural light is shaped with woven shades, tailored drapery, and tonal materials.",
    ],
    coverPosition: "center",
    images: [
      "/images/projects/Houston/PeterS_Houston_3444_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3389_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_2996_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3374_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3406_Final_2.jpg",
      "/images/projects/Houston/PeterS_Houston_2876_Final2.jpg",
      "/images/projects/Houston/PeterS_Houston_2954_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_2936_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_2903_Final_2.jpg",
      "/images/projects/Houston/PeterS_Houston_2837_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_2811_Final.jpg",
      "/images/projects/Houston/005PeterS_Houston_2709_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_2744_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_2794_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3050_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3490_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3056_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3063_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3474_Final.jpg",
      "/images/projects/Houston/hf_20260611_022135_ecf2363e-8903-43c0-963d-97e14aaedebd.png",
      "/images/projects/Houston/PeterS_Houston_3021_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3342_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3311_Final.jpg",
      "/images/projects/Houston/hf_20260611_043031_421d55fd-3e14-4a0c-8539-353686ce800d.jpeg",
      "/images/projects/Houston/PeterS_Houston_3319_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3181_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3148_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3236_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3190_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3282_Final_2.jpg",
      "/images/projects/Houston/PeterS_Houston_3123_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_3094_Final.jpg",
      "/images/projects/Houston/PeterS_Houston_2499_Final.jpg",
    ],
    imageCaptions: [
      "A composed living room balances high ceilings with grounded, tactile furniture.",
      "Woven shades and stone surfaces bring warmth to the architectural envelope.",
      "A sculptural floral moment gives the kitchen a collected, lived-in character.",
    ],
  },
  {
    id: "1",
    title: "Hudson Yards Residence",
    category: "Residential",
    tags: ["New Construction", "Highrise"],
    location: "New York, New York",
    year: "2024",
    image: "/images/projects/Hudson Yards/Sandel_Hudson Yards LR05.jpeg",
    slug: "hudson-yards",
    editorialKicker: "New York Highrise",
    lead: "A highrise residence made intimate through custom drapery, vintage forms, and a tactile palette above the city.",
    description:
      "A Hudson Yards residence featuring custom drapery, bespoke furniture, and sophisticated color. Celadon wool sateen, chocolate upholstery, vintage Paul McCobb pieces, and carefully placed art make the rooms feel personal at altitude.",
    designResponse:
      "The challenge was to soften glass, height, and skyline views without losing the energy of the city. Drapery, texture, and vintage silhouettes give the apartment human scale.",
    details: [
      "Floor-to-ceiling drapery gives the glass architecture softness and control.",
      "Vintage lighting and seating prevent the residence from feeling developer-new.",
      "Color appears in precise, memorable moments rather than broad gestures.",
    ],
    coverPosition: "center",
    images: [
      "/images/projects/Hudson Yards/Sandel_Hudson Yards LR06.jpg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards LR08.jpg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards LR09.jpg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards LR10.jpg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards LR11.jpg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards LR07.jpg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards MBath13.jpeg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards Kitchen12.jpg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards MBR01.jpg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards MBR02.jpg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards MBR04.jpg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards Guest14 Large.jpeg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards Guest15 Large.jpeg",
      "/images/projects/Hudson Yards/Sandel_Hudson Yards Guest16 Large.jpeg",
    ],
    imageCaptions: [
      "Custom wool sateen drapery softens the scale of the highrise glazing.",
      "Vintage seating, sculptural lighting, and layered textures bring intimacy to the city view.",
      "The bedroom uses color and custom bedding as precise, personal gestures.",
    ],
  },
  {
    id: "2",
    title: "Greenwich West",
    category: "Residential",
    tags: ["New Construction", "Highrise"],
    location: "New York, New York",
    year: "2024",
    image: "/images/projects/Greenwich West/110CarltonSt_Oct21-164.jpg",
    slug: "greenwich-west",
    editorialKicker: "Downtown Residence",
    lead: "A downtown highrise shaped by vintage forms, contemporary art, and a calmer version of city living.",
    description:
      "A modern downtown residence featuring a Tacchini Sesann sofa, Adrian Pearsall sled chairs, a Pierre Cardin coffee table, and contemporary artwork by Robert Kelly and Robert Mangold.",
    designResponse:
      "The rooms lean on proportion, art, and singular objects rather than decoration. The result is warm minimalism with enough age and character to feel inhabited.",
    details: [
      "Vintage seating and lighting make the new apartment feel collected.",
      "Large-scale art creates architecture within open rooms.",
      "A softened neutral palette keeps the skyline from overpowering the interiors.",
    ],
    coverPosition: "center",
    images: [
      "/images/projects/Greenwich West/110CarltonSt_Oct21-164.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-169.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-183.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-182.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-193.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-201.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-316.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-276.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-233.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-112.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-150.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-302.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-334.jpg",
      "/images/projects/Greenwich West/110CarltonSt_Oct21-34.jpg",
    ],
    imageCaptions: [
      "The living room is anchored by vintage forms, large-scale art, and downtown light.",
      "Dining balances collectible furniture with everyday clarity.",
      "The bedroom introduces saturated art against a softened architectural envelope.",
    ],
  },
  {
    id: "3",
    title: "Michigan Avenue Penthouse",
    category: "Residential",
    tags: ["Renovation", "Penthouse"],
    location: "Chicago, Illinois",
    year: "2023",
    image: "/images/projects/Michigan Avenue/191018_PeterSandel_01.jpg",
    slug: "michigan-avenue",
    editorialKicker: "Penthouse",
    lead: "A Chicago penthouse where skyline light, important vintage pieces, and sculptural art create a quietly glamorous residence.",
    description:
      "A Chicago penthouse with floor-to-ceiling windows, Vladimir Kagan swivel chairs, a Dorothy Dehner Brutalist sculpture, and a curated contemporary art collection.",
    designResponse:
      "The penthouse needed scale without spectacle. Curved furniture, deep color, and important objects create movement against the rectilinear city backdrop.",
    details: [
      "A round blue rug introduces a focal point without blocking the view.",
      "Sculptural vintage pieces give the glass perimeter warmth and shape.",
      "Art and objects are treated as architecture, not accessories.",
    ],
    coverPosition: "center",
    images: [
      "/images/projects/Michigan Avenue/191018_PeterSandel_02.jpg",
      "/images/projects/Michigan Avenue/191018_PeterSandel_03.jpg",
      "/images/projects/Michigan Avenue/191018_PeterSandel_04.jpg",
      "/images/projects/Michigan Avenue/191018_PeterSandel_06.jpg",
      "/images/projects/Michigan Avenue/191018_PeterSandel_09.jpg",
      "/images/projects/Michigan Avenue/191018_PeterSandel_08.jpg",
      "/images/projects/Michigan Avenue/191018_PeterSandel_05.jpg",
      "/images/projects/Michigan Avenue/191018_PeterSandel_07.jpg",
      "/images/projects/Michigan Avenue/191018_PeterSandel_10.jpg",
    ],
    imageCaptions: [
      "Curved seating and a saturated rug soften the penthouse perimeter.",
      "The skyline remains present, but the furnishings hold the room.",
      "A masculine primary bedroom uses leather, Murano lighting, and sunset views.",
    ],
  },
  {
    id: "4",
    title: "Pool House",
    category: "Residential",
    tags: ["Renovation", "Estate"],
    location: "Asbury Park, NJ",
    year: "2023",
    image: "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2579.jpg",
    slug: "pool-house",
    editorialKicker: "Indoor-Outdoor Living",
    lead: "A garage conversion reimagined as a refined pool house for entertaining, hospitality, and summer ease.",
    description:
      "A pool house conversion with encaustic cement tile floors, custom performance upholstery, an indoor-outdoor entertaining area, a custom kitchenette, and a hideaway bar.",
    designResponse:
      "The space needed to be durable, useful, and charming. Performance materials, custom millwork, and a relaxed hospitality rhythm make the pool house feel considered without becoming precious.",
    details: [
      "Encaustic tile grounds the room with pattern and practicality.",
      "Panel-front appliances keep the kitchenette integrated.",
      "Custom seating and a hideaway bar support entertaining without visual clutter.",
    ],
    coverPosition: "center",
    images: [
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2561.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2665.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2619.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2610.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2627.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2695.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2693.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2753.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2741.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2784.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2743.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2725.jpg",
      "/images/projects/Pool House/220512_TLenz_Sandel_AsburyPark2610 1.jpg",
    ],
    imageCaptions: [
      "Performance materials and tailored furniture make the converted structure feel permanent.",
      "Custom millwork and lighting elevate the bar and kitchenette.",
      "The pool house opens directly into the rituals of outdoor living.",
    ],
  },
  {
    id: "6",
    title: "PS Apartment",
    category: "Residential",
    tags: ["Renovation", "Apartment"],
    location: "New York, New York",
    year: "2020",
    image: "/images/projects/PS Apartment for AD/20_02_17_AD_Peter_Sandel_0222_v2.jpeg",
    slug: "ps-apartment",
    editorialKicker: "Personal Residence",
    lead: "Peter's own apartment, featured in Architectural Digest, distills the studio's instinct for vintage, art, and personal rooms.",
    description:
      "Featured in Architectural Digest, Peter's New York apartment showcases a personal blend of vintage finds, contemporary art, and bespoke furnishings.",
    designResponse:
      "The apartment works as a manifesto: rooms with memory, art with edge, and old pieces used without nostalgia.",
    details: [
      "Personal collecting gives the residence its authority.",
      "Vintage pieces are mixed with contemporary art and custom details.",
      "The apartment shows the studio's design language at its most intimate.",
    ],
    coverPosition: "center",
    images: [
      "/images/projects/PS Apartment for AD/20_02_17_AD_Peter_Sandel_0222_v2.jpeg",
      "/images/projects/PS Apartment for AD/20_02_17_AD_Peter_Sandel_0063+0067_c.jpeg",
      "/images/projects/PS Apartment for AD/20_02_17_AD_Peter_Sandel_0008+0035_C.jpeg",
      "/images/projects/PS Apartment for AD/20_02_17_AD_Peter_Sandel_0196_C.jpeg",
      "/images/projects/PS Apartment for AD/20_02_17_AD_Peter_Sandel_0101_c.jpeg",
      "/images/projects/PS Apartment for AD/20_02_17_AD_Peter_Sandel_0227.jpeg",
      "/images/projects/PS Apartment for AD/20_02_17_AD_Peter_Sandel_0236_C.jpeg",
      "/images/projects/PS Apartment for AD/20_02_17_AD_Peter_Sandel_0265.jpeg",
    ],
    imageCaptions: [
      "A personal room shaped by art, patina, and restraint.",
      "Vintage and contemporary references appear as one fluent language.",
      "Objects, books, and art create the apartment's point of view.",
    ],
  },
  {
    id: "7",
    title: "Design Studio",
    category: "Commercial",
    tags: ["Commercial", "Studio"],
    location: "New York, New York",
    year: "2022",
    image: "/images/projects/PSD Studio 22/SandelDesign-624.jpg",
    slug: "design-studio",
    editorialKicker: "The Studio",
    lead: "The studio workspace reveals the same language Peter brings to clients: edited collections, useful beauty, and rooms that work hard.",
    description:
      "Peter Sandel Design's workspace is a study in mixing vintage and contemporary elements, with custom millwork, Pierre Frey upholstered midcentury chairs, and an archive of materials and artwork.",
    designResponse:
      "The studio balances working infrastructure with a residential sense of detail. Samples, books, objects, and hospitality moments are integrated into the design rather than hidden.",
    details: [
      "Custom millwork turns storage into architecture.",
      "Vintage chairs and textile choices give the workplace character.",
      "Material archives remain visible as part of the studio's creative life.",
    ],
    coverPosition: "center",
    images: [
      "/images/projects/PSD Studio 22/SandelDesign-697.jpg",
      "/images/projects/PSD Studio 22/SandelDesign-646.jpg",
      "/images/projects/PSD Studio 22/SandelDesign-684.jpg",
      "/images/projects/PSD Studio 22/SandelDesign-692.jpg",
      "/images/projects/PSD Studio 22/SandelDesign-676.jpg",
      "/images/projects/PSD Studio 22/SandelDesign_Nov2022-046.jpg",
      "/images/projects/PSD Studio 22/SandelDesign_Nov2022-055.jpg",
      "/images/projects/PSD Studio 22/SandelDesign_Nov2022-104.jpg",
      "/images/projects/PSD Studio 22/SandelDesign_Nov2022-108.jpg",
      "/images/projects/PSD Studio 22/SandelDesign-662.jpg",
    ],
    imageCaptions: [
      "The studio pairs working storage with artful domesticity.",
      "A reupholstered chair and studio library bring personality to the workplace.",
      "Samples and materials are treated as part of the visual language.",
    ],
  },
  {
    id: "10",
    title: "St. Regis Singapore",
    category: "Residential",
    tags: ["Highrise", "International"],
    location: "Singapore",
    year: "2015",
    image: "/images/projects/St Regis Singapore/IMG 0044_rr.jpg",
    slug: "st-regis-singapore",
    editorialKicker: "Singapore Residence",
    lead: "A high-rise residence in Singapore composed with tailored furnishings, collected art, and warm natural materials.",
    description:
      "A St. Regis residential building project in Singapore balancing polished architecture with layered furniture, art, and objects.",
    designResponse:
      "The interiors bring warmth and individuality to a refined tower residence. Wood, textile, art, and sculptural pieces temper the clean architectural envelope and make the apartment feel personal.",
    details: [
      "A glass-walled study and living area keep the apartment open while preserving distinct rooms.",
      "Warm wood furniture and collected artwork soften the high-rise architecture.",
      "Layered accessories and tailored upholstery bring intimacy to the residential tower setting.",
    ],
    coverPosition: "center",
    images: [
      "/images/projects/St Regis Singapore/2100 Singapore Split Shot.jpeg",
      "/images/projects/St Regis Singapore/2100 Dining Singapore.jpeg",
      "/images/projects/St Regis Singapore/2100 Singapore Entry.jpeg",
      "/images/projects/St Regis Singapore/2100 Singapore Coffee Table Close Up.jpeg",
      "/images/projects/St Regis Singapore/IMG 0021_rr.jpg",
      "/images/projects/St Regis Singapore/IMG 0205_rr.jpg",
      "/images/projects/St Regis Singapore/IMG 0219_rr.jpg",
      "/images/projects/St Regis Singapore/IMG 0235_rr.jpg",
      "/images/projects/St Regis Singapore/IMG 0270_rr.jpg",
      "/images/projects/St Regis Singapore/IMG 0283_rr2.jpg",
      "/images/projects/St Regis Singapore/IMG 0295_rr2.jpg",
      "/images/projects/St Regis Singapore/IMG 0303_rr2.jpg",
    ],
    imageCaptions: [
      "Glass, city views, and layered furnishings define the high-rise residence.",
      "Dining balances polished architecture with warm wood and collected artwork.",
      "Entry details introduce texture and craft before the apartment opens to the view.",
    ],
  },
];
